### ISSUE TITLE
Unable to perform cudnn convolution

### ISSUE THREAD

**Issue by HVisMyLife** [coreylowman/cudarc#298]
Hello
I'm trying to setup convolution like that:

    let input_desc = cudnn.create_4d_tensor::<f32>(sys::cudnnTensorFormat_t::CUDNN_TENSOR_NCHW, [1,1,64,64]).unwrap();
    let output_desc = cudnn.create_4d_tensor::<f32>(sys::cudnnTensorFormat_t::CUDNN_TENSOR_NCHW, [1,1,64,64]).unwrap();
    let filter_desc = cudnn.create_4d_filter::<f32>(sys::cudnnTensorFormat_t::CUDNN_TENSOR_NCHW, [1,1,1,1]).unwrap();
    let mut convolution_desc = cudnn.create_conv2d::<f32>([0,0], [1,1], [1,1], sys::cudnnConvolutionMode_t::CUDNN_CONVOLUTION).unwrap();
    convolution_desc.set_math_type(sys::cudnnMathType_t::CUDNN_DEFAULT_MATH).unwrap();
    convolution_desc.set_group_count(1).unwrap();

    let convolution = ConvForward {conv: &convolution_desc, x: &input_desc, w: &filter_desc, y: &output_desc};
    let algo = convolution.pick_algorithm().unwrap();
    let workspace_size = convolution.get_workspace_size(algo).unwrap();

    let matrix = vec![0.5; 64*64];
    let kernel = vec![0.2; 1];
    let matrix_output = vec![0.0; 64*64];

    let src = gpu.htod_copy(matrix).unwrap();
    let filter = gpu.htod_copy(kernel).unwrap();
    let mut dest = gpu.htod_copy(matrix_output).unwrap();
    unsafe {
        let mut workspace = gpu.alloc_zeros::<u8>(workspace_size).unwrap();
        let mut workspace = workspace.transmute_mut::<u8>(workspace_size).unwrap();
        convolution.launch(algo, Some(&mut workspace), (1.,0.), &src, &filter, &mut dest).unwrap();
    }

And it that form (with one element kernel) it works as expected, output is full of 0.1 (0.5*0.2).
However, as soon as I change kernel's dimensions to more than that (for example [1,1,3,3]) it throws `CudnnError(CUDNN_STATUS_BAD_PARAM)` at pick_algorithm()... What I'm doing wrong?

Thanks in advance

**Comment by Jianqoq** [comment]
In code `let mut workspace = workspace.transmute_mut::<u8>(workspace_size).unwrap();
    convolution.launch(algo, Some(&mut workspace), (1.,0.), &src, &filter, &mut dest).unwrap();`, you passed Some(&mut workspace), does cudnn know how to handle the Some enum in Rust?

**Comment by HVisMyLife** [comment]
I've actually fixed it two days ago. It turns out that output have to have exact size. So you either apply padding in convolution description, or reduce output dimesions by kernel width - 1 ( kernel have to have odd side length ). So working example looks like that: 

    let now = Instant::now();
    let gpu = CudaDevice::new(0).unwrap();
    let cudnn = Cudnn::new(gpu.clone()).unwrap();
    println!("Time taken to initialise CUDA: {:.2?}", now.elapsed());

    let input_desc = cudnn.create_4d_tensor::<f32>(sys::cudnnTensorFormat_t::CUDNN_TENSOR_NCHW, [1,1,1024,1024]).unwrap();
    let output_desc = cudnn.create_4d_tensor::<f32>(sys::cudnnTensorFormat_t::CUDNN_TENSOR_NCHW, [1,1,1024-128,1024-128]).unwrap();
    let filter_desc = cudnn.create_4d_filter::<f32>(sys::cudnnTensorFormat_t::CUDNN_TENSOR_NCHW, [1,1,129,129]).unwrap();
    let mut convolution_desc = cudnn.create_conv2d::<f32>([0,0], [1,1], [1,1], sys::cudnnConvolutionMode_t::CUDNN_CROSS_CORRELATION).unwrap();
    convolution_desc.set_math_type(sys::cudnnMathType_t::CUDNN_DEFAULT_MATH).unwrap();
    convolution_desc.set_group_count(1).unwrap();
    
    let convolution = ConvForward {conv: &convolution_desc, x: &input_desc, w: &filter_desc, y: &output_desc};
    let algo = convolution.pick_algorithm().unwrap();
    let workspace_size = convolution.get_workspace_size(algo).unwrap();
    println!("{:?}", algo);
    println!("Workspace size: {:.1?}MB", workspace_size as f32 / 1048576.);

    let matrix = vec![0.5; 1024*1024];
    let kernel = vec![0.2; 129*129];
    let matrix_output = vec![0.0; (1024-128)*(1024-128)];

    let now = Instant::now();
    let src = gpu.htod_copy(matrix).unwrap();
    let filter = gpu.htod_copy(kernel).unwrap();
    let mut dest = gpu.htod_copy(matrix_output).unwrap();
    unsafe {
        let mut workspace = gpu.alloc_zeros::<u8>(workspace_size).unwrap();
        let mut workspace = workspace.transmute_mut::<u8>(workspace_size).unwrap();
        convolution.launch(algo, Some(&mut workspace), (1.,0.), &src, &filter, &mut dest).unwrap();
    }
    let _matrix_output = gpu.sync_reclaim(dest).unwrap();
    println!("Time taken to run: {:.2?}", now.elapsed());

Unfortunately, CUDNN doesn't support arrays bigger than 256 on side [https://docs.nvidia.com/deeplearning/cudnn/backend/latest/api/cudnn-cnn-library.html#cudnnconvolutionforward](url) for FFT convolution (FFT cpu was faster for my than GEMM gpu), so I had to switch to arrayfire, which I think ultimately is better for my use case ( lenia ca ).

Nevertheless, cudarc crate by itself is great, and I will be using it for future projects.
