### ISSUE TITLE
Error: DriverError(CUDA_ERROR_NOT_SUPPORTED, "operation not supported")

### ISSUE THREAD

**Issue by lihongtao1024** [coreylowman/cudarc#484]
The following error occurs when executing cudarc. What could be the reason?

`use cudarc::driver::{CudaContext, CudaSlice, DriverError};

fn main() -> Result<(), DriverError> {
    let ctx = CudaContext::new(0)?;
    let stream = ctx.default_stream();

    // unsafe initialization of unset memory
    let _: CudaSlice<f32> = unsafe { stream.alloc::<f32>(10) }?;

    // this will have memory initialized as 0
    let _: CudaSlice<f64> = stream.alloc_zeros::<f64>(10)?;

    // initialize with slices!
    let _: CudaSlice<usize> = stream.memcpy_stod(&[0; 10])?;
    let _: CudaSlice<u32> = stream.memcpy_stod(&[1, 2, 3])?;

    Ok(())
}`

> Error: DriverError(CUDA_ERROR_NOT_SUPPORTED, "operation not supported")
error: process didn't exit successfully: `target\release\test_cudarc.exe` (exit code: 1)

> PS C:\rabbit-llm\test_cudarc> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Tue_May_27_02:24:01_Pacific_Daylight_Time_2025
Cuda compilation tools, release 12.9, V12.9.86
Build cuda_12.9.r12.9/compiler.36037853_0

> PS C:\rabbit-llm\test_cudarc> nvidia-smi
Fri Nov  7 19:39:38 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.57                 Driver Version: 576.57         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100-SXM2-32GB         TCC   |   00000000:1A:00.0 Off |                    0 |
| N/A   32C    P0             43W /  300W |      10MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla V100-SXM2-32GB         TCC   |   00000000:1B:00.0 Off |                    0 |
| N/A   35C    P0             42W /  300W |      10MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  Tesla V100-SXM2-32GB         TCC   |   00000000:3D:00.0 Off |                    0 |
| N/A   36C    P0             41W /  300W |      10MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  Tesla V100-SXM2-32GB         TCC   |   00000000:3E:00.0 Off |                    0 |
| N/A   35C    P0             44W /  300W |      10MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   4  Tesla V100-SXM2-32GB         TCC   |   00000000:88:00.0 Off |                    0 |
| N/A   32C    P0             40W /  300W |      10MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   5  Tesla V100-SXM2-32GB         TCC   |   00000000:89:00.0 Off |                    0 |
| N/A   38C    P0             43W /  300W |      10MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   6  Tesla V100-SXM2-32GB         TCC   |   00000000:B2:00.0 Off |                    0 |
| N/A   35C    P0             41W /  300W |      10MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   7  Tesla V100-SXM2-32GB         TCC   |   00000000:B3:00.0 Off |                    0 |
| N/A   34C    P0             41W /  300W |      10MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

**Comment by lihongtao1024** [comment]
I debugged and found that any API in the main function works normally when called individually. But as long as they are called in combination, it will report "operation not supported", and I don't understand why. Could it be related to my Windows Server 2025 system? Or is it a compatibility issue because this machine has 8 GPUs?

As follows, it's OK:
`
fn main() -> Result<(), DriverError> {
    // unsafe initialization of unset memory
    let ctx = CudaContext::new(0)?;
    let stream = ctx.default_stream();
    let _: CudaSlice<f32> = unsafe { stream.alloc::<f32>(10) }?;

    // this will have memory initialized as 0
    let ctx = CudaContext::new(0)?;
    let stream = ctx.default_stream();
    let _: CudaSlice<f64> = stream.alloc_zeros::<f64>(10)?;

    // initialize with slices!
    let ctx = CudaContext::new(0)?;
    let stream = ctx.default_stream();
    let _: CudaSlice<usize> = stream.memcpy_stod(&[0; 10])?;

    let ctx = CudaContext::new(0)?;
    let stream = ctx.default_stream();
    let _: CudaSlice<u32> = stream.memcpy_stod(&[1, 2, 3])?;

    Ok(())
}
`

**Comment by lihongtao1024** [comment]
Once the cudarc API has been called, the next call to the API's check_err will detect the error.

`    /// Binds this context to the calling thread. Calling this is key for thread safety.
    pub fn bind_to_thread(&self) -> Result<(), DriverError> {
        self.check_err()?;
        if match result::ctx::get_current()? {
            Some(curr_ctx) => curr_ctx != self.cu_ctx,
            None => true,
        } {
            unsafe { result::ctx::set_current(self.cu_ctx) }?;
        }
        Ok(())
    }`

**Comment by lihongtao1024** [comment]
I found the reason. When using this syntax: let _: CudaSlice<f32> = unsafe { stream.alloc::<f32>(10) }?; , at the end of the call, it will trigger the drop of CudaSlice
, which changes the ctx's error_state to 801. Then when you call the API next time, it will fail. If you assign it a variable name, you can prevent it from being dropped early, and the problem will be solved. But I don't understand why it worked before? This is an official demonstration example. And now my candle isn't working properly, it's reporting this exact error.

>cudarc 0.17.7

> system: windows server 2025

>nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Tue_May_27_02:24:01_Pacific_Daylight_Time_2025
Cuda compilation tools, release 12.9, V12.9.86
Build cuda_12.9.r12.9/compiler.36037853_0

>nvidia-smi
Fri Nov 7 19:39:38 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.57 Driver Version: 576.57 CUDA Version: 12.9 |
|-----------------------------------------+------------------------+----------------------+
| GPU Name Driver-Model | Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. |
| | | MIG M. |
|=========================================+========================+======================|
| 0 Tesla V100-SXM2-32GB TCC | 00000000:1A:00.0 Off | 0 |
| N/A 32C P0 43W / 300W | 10MiB / 32768MiB | 0% Default |
| | | N/A |
+-----------------------------------------+------------------------+----------------------+
| 1 Tesla V100-SXM2-32GB TCC | 00000000:1B:00.0 Off | 0 |
| N/A 35C P0 42W / 300W | 10MiB / 32768MiB | 0% Default |
| | | N/A |
+-----------------------------------------+------------------------+----------------------+
| 2 Tesla V100-SXM2-32GB TCC | 00000000:3D:00.0 Off | 0 |
| N/A 36C P0 41W / 300W | 10MiB / 32768MiB | 0% Default |
| | | N/A |
+-----------------------------------------+------------------------+----------------------+
| 3 Tesla V100-SXM2-32GB TCC | 00000000:3E:00.0 Off | 0 |
| N/A 35C P0 44W / 300W | 10MiB / 32768MiB | 0% Default |
| | | N/A |
+-----------------------------------------+------------------------+----------------------+
| 4 Tesla V100-SXM2-32GB TCC | 00000000:88:00.0 Off | 0 |
| N/A 32C P0 40W / 300W | 10MiB / 32768MiB | 0% Default |
| | | N/A |
+-----------------------------------------+------------------------+----------------------+
| 5 Tesla V100-SXM2-32GB TCC | 00000000:89:00.0 Off | 0 |
| N/A 38C P0 43W / 300W | 10MiB / 32768MiB | 0% Default |
| | | N/A |
+-----------------------------------------+------------------------+----------------------+
| 6 Tesla V100-SXM2-32GB TCC | 00000000:B2:00.0 Off | 0 |
| N/A 35C P0 41W / 300W | 10MiB / 32768MiB | 0% Default |
| | | N/A |
+-----------------------------------------+------------------------+----------------------+
| 7 Tesla V100-SXM2-32GB TCC | 00000000:B3:00.0 Off | 0 |
| N/A 34C P0 41W / 300W | 10MiB / 32768MiB | 0% Default |
| | | N/A |
+-----------------------------------------+------------------------+----------------------+
+-----------------------------------------------------------------------------------------+
| Processes: |
| GPU GI CI PID Type Process name GPU Memory |
| ID ID Usage |
|=========================================================================================|
| No running processes found |
+-----------------------------------------------------------------------------------------+

**Comment by lihongtao1024** [comment]
Maybe the real reason is this: when has_async_alloc==false, malloc_sync is used to allocate cu_device. However, free_async is always used by default in its drop implementation. Therefore, when the object is dropped, you get an 801 error. I think other CUDA objects have the same issue.

**Comment by chelsea0x3b** [comment]
So your context has `has_async_alloc: false`? Have not had a lot of debugging with systems with no async alloc, so I could definitely see `free_async` causing issues - I thought it was just memAllocAsync but it could also be freeAsync. The docs are not very clear here.

**Comment by chelsea0x3b** [comment]
Okay I changed to using free_sync if has_async_alloc is false in 0.17.8. @lihongtao1024 can you see if that resolves?

**Comment by lihongtao1024** [comment]
The problem is solved. Thank you for your help.

**Comment by chelsea0x3b** [comment]
Yay! Ty for the debuggingOn Nov 12, 2025, at 5:14 AM, lihongtao1024 ***@***.***> wrote:﻿lihongtao1024 left a comment (coreylowman/cudarc#484)
The problem is solved. Thank you for your help.
